# See https://docs.codecov.io/docs/codecov-yaml for documentation

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.01%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests"
  - "examples"
  - "vendor/pcg"
