parameters:
  - name: int_blas
    type: boolean
    default: true
  - name: int_lapack
    type: boolean
    default: true
  - name: int_arpack
    type: boolean
    default: true
  - name: int_cxsparse
    type: boolean
    default: true
  - name: int_gmp
    type: boolean
    default: true
  - name: int_glpk
    type: boolean
    default: true
  - name: verify_finally
    type: boolean
    default: true
  - name: build_shared
    type: boolean
    default: false
  - name: enable_tls
    type: boolean
    default: true
  - name: build_type
    type: string
    default: 'RelWithDebInfo'
  - name: extra_cmake_args
    type: string
    default: ''
  - name: extra_ctest_args
    type: string
    default: ''
  - name: use_ccache
    type: boolean
    default: true

steps:
  - task: CMake@1
    displayName: CMake
    inputs:
      cmakeArgs: >
        ..
        -DIGRAPH_USE_INTERNAL_BLAS=${{ parameters.int_blas }}
        -DIGRAPH_USE_INTERNAL_LAPACK=${{ parameters.int_lapack }}
        -DIGRAPH_USE_INTERNAL_ARPACK=${{ parameters.int_arpack }}
        -DIGRAPH_USE_INTERNAL_GLPK=${{ parameters.int_glpk }}
        -DIGRAPH_USE_INTERNAL_CXSPARSE=${{ parameters.int_cxsparse }}
        -DIGRAPH_USE_INTERNAL_GMP=${{ parameters.int_gmp }}
        -DIGRAPH_VERIFY_FINALLY_STACK=${{ parameters.verify_finally }}
        -DBUILD_SHARED_LIBS=${{ parameters.build_shared }}
        -DIGRAPH_ENABLE_TLS=${{ parameters.enable_tls }}
        -DCMAKE_BUILD_TYPE=${{ parameters.build_type }}
        ${{ parameters.extra_cmake_args }}

  - task: Cache@2
    condition: eq('${{ parameters.use_ccache }}', true)
    inputs:
      key: 'ccache | "$(Agent.OS)"'
      path: $(CCACHE_DIR)
    displayName: Ccache

  - task: CMake@1
    displayName: Build
    inputs:
      cmakeArgs: '--build . --target build_tests'

  # TODO: use -j `nproc` on Linux , -j `sysctl -n hw.ncpu` on Darwin
  - script: cd build && ctest -j 4 --output-on-failure ${{ parameters.extra_ctest_args }} --timeout 60
    displayName: Test
