if(MSVC)
  string(APPEND CMAKE_C_FLAGS " /FS")
  string(APPEND CMAKE_CXX_FLAGS " /FS")
endif()

macro(use_all_warnings TARGET_NAME)
  if(MSVC)
    target_compile_options(${TARGET_NAME} PRIVATE /W4)
  else()
    target_compile_options(${TARGET_NAME} PRIVATE -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -Wno-varargs -Wno-sign-compare)
  endif()
endmacro()
