#!/bin/sh

VER=`sed -n -e "s/^PACKAGE_VERSION='\\(.*\\)'$/\1/p" configure`

if [ x$1 = xbzr -o x$1 = x--bzr ]; then
  VER="${VER}~bzr"`date +%Y%m%d`
fi

for i in copyright.in changelog.in control.in; do
  sed "s/@VERSION@/$VER/g" debian/$i > debian/`basename $i .in`
done

echo "Prepared Debian package files for version $VER."
