#!/bin/sh

VER=`sed -n -e "s/^[ \t]*version *= *'\\(.*\\)', *$/\1/p" setup.py`

if test x$1 = xcvs; then
  VER="${VER}-cvs"`date +%Y%m%d`
fi

for i in copyright.in changelog.in control.in; do
  sed "s/@VERSION@/$VER/g" debian/$i > debian/`basename $i .in`
done

