name: MINGW32/MINGW64 - autoconf

on:
  push:
    branches:
      - '**'
      - '!appveyor/**'
      - '!travis/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW32, arch: i686   },
          { msystem: MINGW64, arch: x86_64 }
          ]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Init ${{ matrix.msystem }}-System
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-glpk mingw-w64-${{ matrix.arch }}-gmp mingw-w64-${{ matrix.arch }}-zlib mingw-w64-${{ matrix.arch }}-libxml2
          update: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Configuration
        run: |
          git fetch --prune --unshallow
          ./bootstrap.sh
          mkdir -p build
          cd build
          ../configure -C --enable-tls YFLAGS=-Wall
      - name: Build
        if: ${{ success() }}
        run: make -j V=0 || make
        working-directory: build
      - name: Run Testsuite
        if: ${{ success() }}
        run: make check TESTSUITEFLAGS=-j || make check TESTSUITEFLAGS='-j --recheck -d -v -x'
        working-directory: build
      - name: Generate Artifacts upon Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failure
          path: |
            build/config.*
            build/tests/**
