
#   IGraph R package
#   Copyright (C) 2014  Gabor Csardi <csardi.gabor@gmail.com>
#   334 Harvard street, Cambridge, MA 02139 USA
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc.,  51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301 USA
#
###################################################################

#' @include attributes.R auto.R basic.R bipartite.R centrality.R
#' @include cliques.R cocitation.R cohesive.blocks.R community.R
#' @include components.R console.R conversion.R decomposition.R demo.R
#' @include epi.R fit.R flow.R foreign.R games.R glet.R hrg.R indexing.R
#' @include interface.R iterators.R layout.R minimum.spanning.tree.R
#' @include motifs.R nexus.R operators.R other.R package.R par.R plot.R
#' @include plot.common.R plot.shapes.R pp.R print.R scg.R socnet.R
#' @include sparsedf.R structural.properties.R structure.generators.R
#' @include structure.info.R test.R tkplot.R topology.R
NULL

## For the future, right now, we do not warn or even message

deprecated <- function(old, new) {
  assign(old, new, envir = asNamespace(packageName()))
}

deprecated("add.edges", add_edges)
deprecated("add.vertex.shape", add_shape)
deprecated("add.vertices", add_vertices)
deprecated("adjacent.triangles", count_triangles)
deprecated("articulation.points", articulation_points)
deprecated("aging.prefatt.game", sample_pa_age)
deprecated("aging.ba.game", sample_pa_age)
deprecated("aging.barabasi.game", sample_pa_age)
deprecated("alpha.centrality", alpha_centrality)
deprecated("are.connected", is_connected_to)
deprecated("asPhylo", as_phylo)
deprecated("asPhylo.communities", as_phylo.communities)
deprecated("asPhylo.igraphHRG", as_phylo.igraphHRG)
deprecated("assortativity.degree", assortativity_degree)
deprecated("assortativity.nominal", assortativity_nominal)
deprecated("asymmetric.preference.game", sample_asym_pref)
deprecated("authority.score", authority_score)
deprecated("autocurve.edges", curve_multiple)
deprecated("average.path.length", mean_distance)

deprecated("ba.game", sample_pa)
deprecated("barabasi.game", sample_pa)
deprecated("betweenness.estimate", estimate_betweenness)
deprecated("biconnected.components", biconnected_components)
deprecated("bipartite.mapping", bipartite_mapping)
deprecated("bipartite.projection", bipartite_projection)
deprecated("bipartite.projection.size", bipartite_projection_size)
deprecated("bipartite.random.game", sample_bipartite)
deprecated("blockGraphs", graphs_from_cohesive_blocks)
deprecated("bonpow", power_centrality)

deprecated("callaway.traits.game", sample_traits_callaway)
deprecated("canonical.permutation", canonical_permutation)
deprecated("centralization.betweenness", centr_betw)
deprecated("centralization.betweenness.tmax", centr_betw_tmax)
deprecated("centralization.closeness", centr_clo)
deprecated("centralization.closeness.tmax", centr_clo_tmax)
deprecated("centralization.degree", centr_degree)
deprecated("centralization.degree.tmax", centr_degree_tmax)
deprecated("centralization.evcent", centr_eigen)
deprecated("centralization.evcent.tmax", centr_eigen_tmax)
deprecated("centralize.scores", centralize)
deprecated("cited.type.game", sample_cit_types)
deprecated("citing.cited.type.game", sample_cit_cit_types)
deprecated("clique.number", clique_num)
deprecated("closeness.estimate", estimate_closeness)
deprecated("cluster.distribution", component_distribution)
deprecated("clusters", components)
deprecated("code.length", code_len)
deprecated("cohesive.blocks", cohesive_blocks)
deprecated("compare.communities", compare)
deprecated("connect.neighborhood", connect)
deprecated("contract.vertices", contract)
deprecated("convex.hull", convex_hull)
deprecated("count.multiple", count_multiple)
deprecated("cutat", cut_at)

deprecated("decompose.graph", decompose)
deprecated("degree.distribution", degree_distribution)
deprecated("degree.sequence.game", sample_degseq)
deprecated("delete.edges", delete_edges)
deprecated("delete.vertices", delete_vertices)
deprecated("dendPlot", plot_dendrogram)
deprecated("dendPlot.communities", plot_dendrogram.communities)
deprecated("dendPlot.igraphHRG", plot_dendrogram.igraphHRG)
deprecated("dominator.tree", dominator_tree)
deprecated("dyad.census", dyad_census)

deprecated("ecount", gsize)
deprecated("edge.betweenness", edge_betweenness)
deprecated("edge.betweenness.community", cluster_edge_betweenness)
deprecated("edge.betweenness.estimate", estimate_edge_betweenness)
deprecated("edge.connectivity", edge_connectivity)
deprecated("edge.disjoint.paths", edge_disjoint_paths)
deprecated("establishment.game", sample_traits)
deprecated("evcent", eigen_centrality)

deprecated("farthest.nodes", farthest_vertices)
deprecated("fastgreedy.community", cluster_fast_greedy)
deprecated("forest.fire.game", sample_forestfire)

deprecated("get.adjedgelist", as_adj_edge_list)
deprecated("get.adjlist", as_adj_list)
deprecated("get.adjacency", as_adj)
deprecated("get.data.frame", as_data_frame)
deprecated("get.edge.attribute", edge_attr)
deprecated("get.edgelist", as_edgelist)
deprecated("get.graph.attribute", graph_attr)
deprecated("get.incidence", as_incidence_matrix)
deprecated("get.stochastic", stochastic_matrix)
deprecated("get.vertex.attribute", vertex_attr)
deprecated("graph.adhesion", adhesion)
deprecated("graph.adjacency", graph_from_adjacency_matrix)
deprecated("graph.adjlist", graph_from_adj_list)
deprecated("graph.atlas", graph_atlas)
deprecated("graph.automorphisms", automorphisms)
deprecated("graph.bfs", bfs)
deprecated("graph.bipartite", bipartite_graph)
deprecated("graph.cohesion", cohesion)
deprecated("graph.complementer", complementer)
deprecated("graph.compose", compose)
deprecated("graph.coreness", coreness)
deprecated("graph.data.frame", graph_from_data_frame)
deprecated("graph.de.bruijn", de_bruijn_graph)
deprecated("graph.density", density)
deprecated("graph.disjoint.union", disjoint_union)
deprecated("graph.dfs", dfs)
deprecated("graph.difference", difference)
deprecated("graph.diversity", diversity)
deprecated("graph.edgelist", graph_from_edgelist)
deprecated("graph.eigen", spectrum)
deprecated("graph.empty", empty_graph)
deprecated("graph.extended.chordal.ring", chordal_ring)
deprecated("graph.formula", graph_from_formula)
deprecated("graph.full", full_graph)
deprecated("graph.full.bipartite", full_bipartite_graph)
deprecated("graph.full.citation", full_citation_graph)
deprecated("graph.graphdb", graph_from_graphdb)
deprecated("graph.incidence", graph_from_incidence_matrix)
deprecated("graph.isoclass", iso_class)
deprecated("graph.isocreate", graph_from_iso_class)
deprecated("graph.kautz", kautz_graph)
deprecated("graph.knn", knn)
deprecated("graph.laplacian", laplacian_matrix)
deprecated("graph.lattice", lattice)
deprecated("graph.lcf", graph_from_lcf)
deprecated("graph.maxflow", max_flow)
deprecated("graph.mincut", min_cut)
deprecated("graph.motifs", motifs)
deprecated("graph.motifs.est", sample_motifs)
deprecated("graph.motifs.no", count_motifs)
deprecated("graph.neighborhood", ego_graph)
deprecated("graph.star", star)
deprecated("graph.strength", strength)
deprecated("graph.tree", tree)
deprecated("graph.union", union)
deprecated("graph.ring", ring)
deprecated("graphlets.candidate.basis", graphlet_basis)
deprecated("graphlets.project", graphlet_proj)
deprecated("growing.random.game", sample_growing)
deprecated("grg.game", sample_grg)

deprecated("has.multiple", any_multiple)
deprecated("hrg.consensus", consensus_tree)
deprecated("hrg.create", hrg)
deprecated("hrg.dendrogram", hrg_tree)
deprecated("hrg.game", sample_hrg)
deprecated("hrg.fit", fit_hrg)
deprecated("hrg.predict", predict_edges)
deprecated("hub.score", hub_score)

deprecated("igraph.arpack.default", arpack_defaults)
deprecated("igraph.console", console)
deprecated("igraph.eigen.default", eigen_defaults)
deprecated("igraph.sample", sample_seq)
deprecated("igraph.version", igraph_version)
deprecated("igraphdemo", igraph_demo)
deprecated("igraphtest", igraph_test)
deprecated("independence.number", ivs_size)
deprecated("independent.vertex.sets", ivs)
deprecated("infomap.community", cluster_infomap)
deprecated("induced.subgraph", induced_subgraph)
deprecated("interconnected.islands.game", sample_islands)
deprecated("is.bipartite", is_bipartite)
deprecated("is.chordal", is_chordal)
deprecated("is.connected", is_connected)
deprecated("is.dag", is_dag)
deprecated("is.degree.sequence", is_degseq)
deprecated("is.directed", is_directed)
deprecated("is.graphical.degree.sequence", is_graphical)
deprecated("is.hierarchical", is_hierarchical)
deprecated("is.igraph", is_igraph)
deprecated("is.loop", which_loop)
deprecated("is.matching", is_matching)
deprecated("is.maximal.matching", is_max_matching)
deprecated("is.minimal.separator", is_min_separator)
deprecated("is.multiple", which_multiple)
deprecated("is.mutual", which_mutual)
deprecated("is.named", is_named)
deprecated("is.separator", is_separator)
deprecated("is.simple", is_simple)
deprecated("is.weighted", is_weighted)

deprecated("k.regular.game", sample_k_regular)

deprecated("label.propagation.community", cluster_label_prop)
deprecated("largest.cliques", largest_cliques)
deprecated("largest.independent.vertex.sets", largest_ivs)
deprecated("lastcit.game", sample_last_cit)
deprecated("layout.auto", layout_nicely)
deprecated("layout.bipartite", layout_as_bipartite)
deprecated("layout.circle", layout_in_circle)
deprecated("layout.davidson.harel", layout_with_dh)
deprecated("layout.drl", layout_with_drl)
deprecated("layout.fruchterman.reingold", layout_with_fr)
deprecated("layout.gem", layout_with_gem)
deprecated("layout.graphopt", layout_with_graphopt)
deprecated("layout.grid", layout_on_grid)
deprecated("layout.kamada.kawai", layout_with_kk)
deprecated("layout.lgl", layout_with_lgl)
deprecated("layout.mds", layout_with_mds)
deprecated("layout.merge", merge_coords)
deprecated("layout.norm", norm_coords)
deprecated("layout.random", layout_randomly)
deprecated("layout.reingold.tilford", layout_as_tree)
deprecated("layout.sphere", layout_on_sphere)
deprecated("layout.star", layout_as_star)
deprecated("layout.sugiyama", layout_with_sugiyama)
deprecated("leading.eigenvector.community", cluster_leading_eigen)
deprecated("line.graph", line_graph)
deprecated("list.edge.attributes", edge_attr_names)
deprecated("list.graph.attributes", graph_attr_names)
deprecated("list.vertex.attributes", vertex_attr_names)

deprecated("maxcohesion", max_cohesion)
deprecated("maximal.cliques", max_cliques)
deprecated("maximal.cliques.count", count_max_cliques)
deprecated("maximal.independent.vertex.sets", maximal_ivs)
deprecated("minimal.st.separators", min_st_separators)
deprecated("maximum.bipartite.matching", max_bipartite_match)
deprecated("maximum.cardinality.search", max_cardinality)
deprecated("minimum.size.separators", min_separators)
deprecated("minimum.spanning.tree", mst)
deprecated("mod.matrix", modularity_matrix)
deprecated("multilevel.community", cluster_louvain)

deprecated("neighborhood", ego)
deprecated("neighborhood.size", ego_size)
deprecated("nexus.get", nexus_get)
deprecated("nexus.info", nexus_info)
deprecated("nexus.list", nexus_list)
deprecated("nexus.search", nexus_search)
deprecated("no.clusters", count_components)

deprecated("optimal.community", cluster_optimal)

deprecated("page.rank", page_rank)
deprecated("page.rank.old", page_rank_old)
deprecated("path.length.hist", distance_table)
deprecated("permute.vertices", permute)
deprecated("piecewise.layout", layout_components)
deprecated("plotHierarchy", plot_hierarchy)
deprecated("power.law.fit", fit_power_law)
deprecated("preference.game", sample_pref)

deprecated("read.graph", read_graph)
deprecated("remove.edge.attribute", delete_edge_attr)
deprecated("remove.graph.attribute", delete_graph_attr)
deprecated("remove.vertex.attribute", delete_vertex_attr)
deprecated("running.mean", running_mean)

deprecated("sbm.game", sample_sbm)
deprecated("scgGrouping", scg_group)
deprecated("scgNormEps", scg_eps)
deprecated("scgSemiProjectors", scg_semi_proj)
deprecated("set.edge.attribute", set_edge_attr)
deprecated("set.graph.attribute", set_graph_attr)
deprecated("set.vertex.attribute", set_vertex_attr)
deprecated("shortest.paths", distances)
deprecated("showtrace", show_trace)
deprecated("spinglass.community", cluster_spinglass)
deprecated("stCuts", st_cuts)
deprecated("stMincuts", st_min_cuts)
deprecated("static.fitness.game", sample_fitness)
deprecated("statis.power.law.game", sample_fitness_pl)
deprecated("subgraph.centrality", subgraph_centrality)

deprecated("tkplot.canvas", tk_canvas)
deprecated("tkplot.center", tk_center)
deprecated("tkplot.close", tk_close)
deprecated("tkplot.export.postscript", tk_postscript)
deprecated("tkplot.fit.to.screen", tk_fit)
deprecated("tkplot.getcoords", tk_coords)
deprecated("tkplot.off", tk_off)
deprecated("tkplot.reshape", tk_reshape)
deprecated("tkplot.rotate", tk_rotate)
deprecated("tkplot.setcoords", tk_set_coords)

deprecated("topological.sort", topo_sort)
deprecated("triad.census", triad_census)

deprecated("unfold.tree", unfold_tree)

deprecated("vcount", gorder)
deprecated("vertex.connectivity", vertex_connectivity)
deprecated("vertex.disjoint.paths", vertex_disjoint_paths)

deprecated("walktrap.community", cluster_walktrap)
deprecated("watts.strogatz.game", sample_smallworld)
deprecated("write.graph", write_graph)
