
#   IGraph R package
#   Copyright (C) 2006-2012  Gabor Csardi <csardi.gabor@gmail.com>
#   334 Harvard street, Cambridge, MA 02139 USA
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc.,  51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301 USA
#
###################################################################

graph.get.isomorphisms.vf2 <- function(graph1, graph2, vertex.color1,
                                       vertex.color2, edge.color1,
                                       edge.color2) {
  # Argument checks
  if (!is.igraph(graph1)) { stop("Not a graph object") }
  if (!is.igraph(graph2)) { stop("Not a graph object") }
  if (missing(vertex.color1)) { 
    if ("color" %in% list.vertex.attributes(graph1)) { 
      vertex.color1 <- V(graph1)$color 
    } else { 
      vertex.color1 <- NULL 
    } 
  } 
  if (!is.null(vertex.color1)) { 
    vertex.color1 <- as.integer(vertex.color1)-1L 
  }
  if (missing(vertex.color2)) { 
    if ("color" %in% list.vertex.attributes(graph2)) { 
      vertex.color2 <- V(graph2)$color 
    } else { 
      vertex.color2 <- NULL 
    } 
  } 
  if (!is.null(vertex.color2)) { 
    vertex.color2 <- as.integer(vertex.color2)-1L 
  }
  if (missing(edge.color1)) { 
    if ("color" %in% list.edge.attributes(graph1)) { 
      edge.color1 <- E(graph1)$color 
    } else { 
      edge.color1 <- NULL 
    } 
  } 
  if (!is.null(edge.color1)) { 
    edge.color1 <- as.integer(edge.color1)-1L 
  }
  if (missing(edge.color2)) { 
    if ("color" %in% list.edge.attributes(graph2)) { 
      edge.color2 <- E(graph2)$color 
    } else { 
      edge.color2 <- NULL 
    } 
  } 
  if (!is.null(edge.color2)) { 
    edge.color2 <- as.integer(edge.color2)-1L 
  }

  on.exit( .Call("R_igraph_finalizer", PACKAGE="igraph") )
  # Function call
  res <- .Call("R_igraph_get_isomorphisms_vf2", graph1, graph2, vertex.color1,
               vertex.color2, edge.color1, edge.color2,
               PACKAGE="igraph")
  
  res <- lapply(res, "+", 1)

  if (getIgraphOpt("add.vertex.names") && is.named(graph2)) {
    for (i in seq_along(res)) {
      names(res[[i]]) <- V(graph2)$name[ res[[i]] ]
    }
  }
  res
}

graph.get.subisomorphisms.vf2 <- function(graph1, graph2, vertex.color1,
                                          vertex.color2, edge.color1,
                                          edge.color2) {
  # Argument checks
  if (!is.igraph(graph1)) { stop("Not a graph object") }
  if (!is.igraph(graph2)) { stop("Not a graph object") }
  if (missing(vertex.color1)) { 
    if ("color" %in% list.vertex.attributes(graph1)) { 
      vertex.color1 <- V(graph1)$color 
    } else { 
      vertex.color1 <- NULL 
    } 
  } 
  if (!is.null(vertex.color1)) { 
    vertex.color1 <- as.integer(vertex.color1)-1L 
  }
  if (missing(vertex.color2)) { 
    if ("color" %in% list.vertex.attributes(graph2)) { 
      vertex.color2 <- V(graph2)$color 
    } else { 
      vertex.color2 <- NULL 
    } 
  } 
  if (!is.null(vertex.color2)) { 
    vertex.color2 <- as.integer(vertex.color2)-1L 
  }
  if (missing(edge.color1)) { 
    if ("color" %in% list.edge.attributes(graph1)) { 
      edge.color1 <- E(graph1)$color 
    } else { 
      edge.color1 <- NULL 
    } 
  } 
  if (!is.null(edge.color1)) { 
    edge.color1 <- as.integer(edge.color1)-1L 
  }
  if (missing(edge.color2)) { 
    if ("color" %in% list.edge.attributes(graph2)) { 
      edge.color2 <- E(graph2)$color 
    } else { 
      edge.color2 <- NULL 
    } 
  } 
  if (!is.null(edge.color2)) { 
    edge.color2 <- as.integer(edge.color2)-1L 
  }

  on.exit( .Call("R_igraph_finalizer", PACKAGE="igraph") )
  # Function call
  res <- .Call("R_igraph_get_subisomorphisms_vf2", graph1, graph2,
               vertex.color1, vertex.color2, edge.color1, edge.color2,
               PACKAGE="igraph")

  res <- lapply(res, "+", 1)

  if (getIgraphOpt("add.vertex.names") && is.named(graph2)) {
    for (i in seq_along(res)) {
      names(res[[i]]) <- V(graph2)$name[ res[[i]] ]
    }
  }
  res
}

graph.isoclass.subgraph <- function(graph, vids) {
  # Argument checks
  if (!is.igraph(graph)) { stop("Not a graph object") }
  vids <- as.igraph.vs(graph, vids)-1

  on.exit( .Call("R_igraph_finalizer", PACKAGE="igraph") )
  # Function call
  res <- .Call("R_igraph_isoclass_subgraph", graph, vids,
        PACKAGE="igraph")
  res
}

# Rest generated by stimulus

